apiVersion: v1
kind: Service
metadata:
    name: txnreqbackend
    labels:
        name: txnreqbackend
        app: demo-txn-app
spec:
    ports:
    - port: 6379
      targetPort: 6379
    selector:
        name: txn-redis-pod
        app: demo-txn-app