apiVersion: v1
kind: Pod
metadata:
    name: txn-portal-pod
    labels:
        name: txn-portal-pod
        app: demo-txn-app
spec:
    containers:
    - name: txn-portal
      image: rishabhsagar/txndemo:portal
      ports:
      - containerPort: 5000 
