apiVersion: v1
kind: Service
metadata:
    name: txn-portal-service
    labels:
        name: txn-portal-service
        app: demo-txn-app
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
    selector:
        name: txn-portal-pod
        app: demo-txn-app